"""ajout du status dans la table users; creation d'une table parametre; modification de la tapble pointage selon la nouvelle logique de gestion

Revision ID: 1b524c58d7b8
Revises: d69d7c24af95
Create Date: 2026-06-16 16:42:36.643885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1b524c58d7b8'
down_revision: Union[str, Sequence[str], None] = 'd69d7c24af95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=True),
    sa.Column('valeur', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.add_column('pointages', sa.Column('minutes_travail', sa.Integer(), nullable=True))
    op.add_column('pointages', sa.Column('minutes_sup', sa.Integer(), nullable=True))
    op.add_column('pointages', sa.Column('numero_pointage', sa.Integer(), nullable=False))
    op.add_column('pointages', sa.Column('distance_arrivee', sa.Integer(), nullable=True))
    op.add_column('pointages', sa.Column('distance_depart', sa.Integer(), nullable=True))
    op.add_column('pointages', sa.Column('status_arrivee', sa.Enum('ABSENT', 'PENDING', 'PRESENT', 'RETARD', name='scoringstate'), nullable=True))
    op.add_column('pointages', sa.Column('status_depart', sa.Enum('ABSENT', 'PENDING', 'PRESENT', 'RETARD', name='scoringstate'), nullable=True))
    op.add_column('pointages', sa.Column('photo_pointage_arrivee', sa.String(length=100), nullable=True))
    op.add_column('pointages', sa.Column('photo_pointage_depart', sa.String(length=100), nullable=True))
    op.drop_column('pointages', 'status')
    op.drop_column('pointages', 'photo_pointage')
    op.drop_column('pointages', 'heure_travail')
    op.add_column('users', sa.Column('status', sa.Enum('actif', 'inactif'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.add_column('pointages', sa.Column('heure_travail', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('pointages', sa.Column('photo_pointage', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('pointages', sa.Column('status', mysql.ENUM('ABSENT', 'PENDING', 'PRESENT_PARTIEL', 'PRESENT', 'RETARD', 'RETARD_PRESENT'), nullable=True))
    op.drop_column('pointages', 'photo_pointage_depart')
    op.drop_column('pointages', 'photo_pointage_arrivee')
    op.drop_column('pointages', 'status_depart')
    op.drop_column('pointages', 'status_arrivee')
    op.drop_column('pointages', 'distance_depart')
    op.drop_column('pointages', 'distance_arrivee')
    op.drop_column('pointages', 'numero_pointage')
    op.drop_column('pointages', 'minutes_sup')
    op.drop_column('pointages', 'minutes_travail')
    op.drop_table('parametres')
    # ### end Alembic commands ###
