"""mise à jour du model demande

Revision ID: 2701b49d9cc2
Revises: a507eba440a2
Create Date: 2026-05-27 06:14:53.312735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2701b49d9cc2'
down_revision: Union[str, Sequence[str], None] = 'a507eba440a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscritions', sa.Column('date_req', sa.Date(), nullable=True))
    op.add_column('inscritions', sa.Column('hour_req', sa.Time(), nullable=True))
    op.alter_column('inscritions', 'status',
               existing_type=mysql.ENUM('accepted', 'refused', ''),
               type_=sa.Enum('accepted', 'refused', 'pending'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscritions', 'status',
               existing_type=sa.Enum('accepted', 'refused', 'pending'),
               type_=mysql.ENUM('accepted', 'refused', ''),
               existing_nullable=True)
    op.drop_column('inscritions', 'hour_req')
    op.drop_column('inscritions', 'date_req')
    # ### end Alembic commands ###
