"""Inclure les tables de la bd dans la migration migration

Revision ID: 376558de9129
Revises: aacf804f0f72
Create Date: 2026-05-19 16:53:09.564782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376558de9129'
down_revision: Union[str, Sequence[str], None] = 'aacf804f0f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Demande_inscrition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=True),
    sa.Column('matricule', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=True),
    sa.Column('matricule', sa.String(length=7), nullable=True),
    sa.Column('sexe', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('qrCode', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('total_presence', sa.Integer(), nullable=True),
    sa.Column('total_absence', sa.Integer(), nullable=True),
    sa.Column('total_retard', sa.Integer(), nullable=True),
    sa.Column('total_heure_travail', sa.Integer(), nullable=True),
    sa.Column('total_heure_sup', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('heure_arrive', sa.Time(), nullable=True),
    sa.Column('heure_depart', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('photo_pointage', sa.String(length=100), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pointages')
    op.drop_table('users')
    op.drop_table('Demande_inscrition')
    # ### end Alembic commands ###
