"""ajout de la tables statistique et mise à jour des tables existantes

Revision ID: 3abfe58b0eb1
Revises: 376558de9129
Create Date: 2026-05-20 10:52:50.063834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3abfe58b0eb1'
down_revision: Union[str, Sequence[str], None] = '376558de9129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Demande_inscrition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=False),
    sa.Column('prenom', sa.String(length=30), nullable=False),
    sa.Column('sexe', sa.Enum('MASCULIN', 'FEMININ', name='sexe'), nullable=False),
    sa.Column('matricule', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('statistiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_periode', sa.String(length=20), nullable=True),
    sa.Column('date_debuit', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('mois', sa.Integer(), nullable=True),
    sa.Column('Année', sa.Integer(), nullable=True),
    sa.Column('nb_pesence', sa.Integer(), nullable=True),
    sa.Column('nb_absence', sa.Integer(), nullable=True),
    sa.Column('nb_retard', sa.Integer(), nullable=True),
    sa.Column('total_heure_travailé', sa.Integer(), nullable=True),
    sa.Column('total_heure_sup', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('pointages', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('pointages', 'heure_arrive',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('pointages', 'heure_depart',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('pointages', 'status',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Enum('PRESENT', 'ABSENT', 'PENDING', name='scoringstate'),
               nullable=False)
    op.alter_column('pointages', 'photo_pointage',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('users', sa.Column('prenom', sa.String(length=30), nullable=False))
    op.alter_column('users', 'nom',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=30),
               nullable=False)
    op.alter_column('users', 'sexe',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('MASCULIN', 'FEMININ', name='sexe'),
               nullable=False)
    op.alter_column('users', 'matricule',
               existing_type=mysql.VARCHAR(length=7),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('users', 'photo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['telephone'])
    op.drop_column('users', 'type')
    op.drop_column('users', 'total_retard')
    op.drop_column('users', 'total_heure_travail')
    op.drop_column('users', 'total_absence')
    op.drop_column('users', 'total_presence')
    op.drop_column('users', 'total_heure_sup')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_heure_sup', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_presence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_absence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_heure_travail', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('total_retard', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'photo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'matricule',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('users', 'sexe',
               existing_type=sa.Enum('MASCULIN', 'FEMININ', name='sexe'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'nom',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('users', 'prenom')
    op.alter_column('pointages', 'photo_pointage',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('pointages', 'status',
               existing_type=sa.Enum('PRESENT', 'ABSENT', 'PENDING', name='scoringstate'),
               type_=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('pointages', 'heure_depart',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('pointages', 'heure_arrive',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('pointages', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('statistiques')
    op.drop_table('Demande_inscrition')
    # ### end Alembic commands ###
