"""correction de la relation entre employé et pointage

Revision ID: 4ae1cc74c02d
Revises: e1e73dc12525
Create Date: 2026-05-21 11:29:02.400681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ae1cc74c02d'
down_revision: Union[str, Sequence[str], None] = 'e1e73dc12525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistiques', sa.Column('Annee', sa.Integer(), nullable=True))
    op.add_column('statistiques', sa.Column('total_heure_travail', sa.Integer(), nullable=True))
    op.drop_column('statistiques', 'total_heure_travailé')
    op.drop_column('statistiques', 'Année')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistiques', sa.Column('Année', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('statistiques', sa.Column('total_heure_travailé', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('statistiques', 'total_heure_travail')
    op.drop_column('statistiques', 'Annee')
    # ### end Alembic commands ###
