"""ajout suppression de l'incrementation de l'id des paramettres

Revision ID: 64fe7517a06c
Revises: 1b524c58d7b8
Create Date: 2026-06-17 18:01:31.096132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fe7517a06c'
down_revision: Union[str, Sequence[str], None] = '1b524c58d7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
