"""mise a jour des états de pointage

Revision ID: 723ead315bce
Revises: 8e8ae6cf4be4
Create Date: 2026-06-02 05:51:12.064901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723ead315bce'
down_revision: Union[str, Sequence[str], None] = '8e8ae6cf4be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
