"""mise à jour du model demande

Revision ID: 8c3f9316d427
Revises: 2701b49d9cc2
Create Date: 2026-05-27 08:53:46.240226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c3f9316d427'
down_revision: Union[str, Sequence[str], None] = '2701b49d9cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscritions', 'date_req',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('inscritions', 'hour_req',
               existing_type=mysql.TIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inscritions', 'hour_req',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('inscritions', 'date_req',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
