"""mise a jour des états de pointage

Revision ID: 8e8ae6cf4be4
Revises: b4dc0efcda0c
Create Date: 2026-06-02 05:41:38.529177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8ae6cf4be4'
down_revision: Union[str, Sequence[str], None] = 'b4dc0efcda0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
