"""ajout du champ comptabilisant les heurs d'absence dans statistique

Revision ID: a507eba440a2
Revises: 4ae1cc74c02d
Create Date: 2026-05-21 17:08:56.970976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a507eba440a2'
down_revision: Union[str, Sequence[str], None] = '4ae1cc74c02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistiques', sa.Column('total_heure_absent', sa.Time(), nullable=True))
    op.alter_column('statistiques', 'total_heure_travail',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('statistiques', 'total_heure_sup',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Time(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistiques', 'total_heure_sup',
               existing_type=sa.Time(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('statistiques', 'total_heure_travail',
               existing_type=sa.Time(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('statistiques', 'total_heure_absent')
    # ### end Alembic commands ###
