"""chagement du type des distance en double

Revision ID: a77e157bef5b
Revises: 64fe7517a06c
Create Date: 2026-06-23 22:45:56.584824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a77e157bef5b'
down_revision: Union[str, Sequence[str], None] = '64fe7517a06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pointages', 'distance_arrivee',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Double(),
               existing_nullable=True)
    op.alter_column('pointages', 'distance_depart',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Double(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pointages', 'distance_depart',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('pointages', 'distance_arrivee',
               existing_type=sa.Double(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###
