"""Inclure les tables de la bd dans la migration migration

Revision ID: aacf804f0f72
Revises: c9b7cfe7254f
Create Date: 2026-05-19 16:31:54.055828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacf804f0f72'
down_revision: Union[str, Sequence[str], None] = 'c9b7cfe7254f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
