"""mise a jour de la table statistiques

Revision ID: b4dc0efcda0c
Revises: 8c3f9316d427
Create Date: 2026-06-02 03:58:18.312430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4dc0efcda0c'
down_revision: Union[str, Sequence[str], None] = '8c3f9316d427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pointages', sa.Column('date_day', sa.Date(), nullable=False))
    op.add_column('pointages', sa.Column('heure_travail', sa.Integer(), nullable=True))
    op.alter_column('pointages', 'heure_arrive',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('pointages', 'heure_depart',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('pointages', 'status',
               existing_type=mysql.ENUM('PRESENT', 'ABSENT', 'PENDING'),
               nullable=True)
    op.alter_column('pointages', 'photo_pointage',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('pointages', 'date')
    op.add_column('statistiques', sa.Column('date_debut', sa.Date(), nullable=True))
    op.add_column('statistiques', sa.Column('nb_presence', sa.Integer(), nullable=True))
    op.add_column('statistiques', sa.Column('total_minutes_travail', sa.Integer(), nullable=True))
    op.add_column('statistiques', sa.Column('total_minutes_sup', sa.Integer(), nullable=True))
    op.add_column('statistiques', sa.Column('total_minutes_absence', sa.Integer(), nullable=True))
    op.drop_column('statistiques', 'mois')
    op.drop_column('statistiques', 'total_heure_absent')
    op.drop_column('statistiques', 'nb_pesence')
    op.drop_column('statistiques', 'Annee')
    op.drop_column('statistiques', 'date_debuit')
    op.drop_column('statistiques', 'total_heure_sup')
    op.drop_column('statistiques', 'total_heure_travail')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistiques', sa.Column('total_heure_travail', mysql.TIME(), nullable=True))
    op.add_column('statistiques', sa.Column('total_heure_sup', mysql.TIME(), nullable=True))
    op.add_column('statistiques', sa.Column('date_debuit', sa.DATE(), nullable=True))
    op.add_column('statistiques', sa.Column('Annee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('statistiques', sa.Column('nb_pesence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('statistiques', sa.Column('total_heure_absent', mysql.TIME(), nullable=True))
    op.add_column('statistiques', sa.Column('mois', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('statistiques', 'total_minutes_absence')
    op.drop_column('statistiques', 'total_minutes_sup')
    op.drop_column('statistiques', 'total_minutes_travail')
    op.drop_column('statistiques', 'nb_presence')
    op.drop_column('statistiques', 'date_debut')
    op.add_column('pointages', sa.Column('date', sa.DATE(), nullable=False))
    op.alter_column('pointages', 'photo_pointage',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pointages', 'status',
               existing_type=mysql.ENUM('PRESENT', 'ABSENT', 'PENDING'),
               nullable=False)
    op.alter_column('pointages', 'heure_depart',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('pointages', 'heure_arrive',
               existing_type=mysql.TIME(),
               nullable=False)
    op.drop_column('pointages', 'heure_travail')
    op.drop_column('pointages', 'date_day')
    # ### end Alembic commands ###
