"""Initial migration

Revision ID: c9b7cfe7254f
Revises: 
Create Date: 2026-05-19 15:41:50.488699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9b7cfe7254f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_job_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_job_execution_log_job_name'), 'cron_job_execution_log', ['job_name'], unique=False)
    op.create_table('cron_job_state',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_run', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('cron_job_status',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('instance_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('pointages')
    op.drop_table('administrateurs')
    op.drop_index(op.f('email'), table_name='employes')
    op.drop_index(op.f('matricule'), table_name='employes')
    op.drop_table('employes')
    op.drop_index(op.f('matricule'), table_name='demande_inscrition')
    op.drop_table('demande_inscrition')
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('matricule'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('matricule', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('sexe', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('photo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('qrCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poste', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_presence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_absence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_retard', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_heure_travail', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_heure_sup', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('matricule'), 'users', ['matricule'], unique=True)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.create_table('demande_inscrition',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('matricule', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('photo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poste', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('matricule'), 'demande_inscrition', ['matricule'], unique=True)
    op.create_table('employes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('matricule', mysql.VARCHAR(length=7), nullable=True),
    sa.Column('sexe', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('photo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('qrCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('poste', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_presence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_absence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_retard', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_heure_travail', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('total_heure_sup', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('matricule'), 'employes', ['matricule'], unique=True)
    op.create_index(op.f('email'), 'employes', ['email'], unique=True)
    op.create_table('administrateurs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['employes.id'], name=op.f('administrateurs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pointages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('heure', mysql.TIME(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('photo_pointage', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('pointages_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('cron_job_status')
    op.drop_table('cron_job_state')
    op.drop_index(op.f('ix_cron_job_execution_log_job_name'), table_name='cron_job_execution_log')
    op.drop_table('cron_job_execution_log')
    # ### end Alembic commands ###
