"""mise regeneration des tables 

Revision ID: d69d7c24af95
Revises: 3d4c279d4b88
Create Date: 2026-06-07 07:14:11.404326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69d7c24af95'
down_revision: Union[str, Sequence[str], None] = '3d4c279d4b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscritions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=False),
    sa.Column('prenom', sa.String(length=30), nullable=False),
    sa.Column('sexe', sa.Enum('MASCULIN', 'FEMININ', name='sexe'), nullable=False),
    sa.Column('matricule', sa.String(length=6), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('date_req', sa.Date(), nullable=False),
    sa.Column('hour_req', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'refused', 'pending'), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.Date(), nullable=False),
    sa.Column('heure_arrive', sa.Time(), nullable=True),
    sa.Column('heure_depart', sa.Time(), nullable=True),
    sa.Column('heure_travail', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ABSENT', 'PENDING', 'PRESENT_PARTIEL', 'PRESENT', 'RETARD', 'RETARD_PRESENT', name='scoringstate'), nullable=True),
    sa.Column('photo_pointage', sa.String(length=100), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statistiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_periode', sa.String(length=20), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('nb_presence', sa.Integer(), nullable=True),
    sa.Column('nb_absence', sa.Integer(), nullable=True),
    sa.Column('nb_retard', sa.Integer(), nullable=True),
    sa.Column('total_minutes_travail', sa.Integer(), nullable=True),
    sa.Column('total_minutes_sup', sa.Integer(), nullable=True),
    sa.Column('total_minutes_absence', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistiques')
    op.drop_table('pointages')
    op.drop_table('inscritions')
    # ### end Alembic commands ###
