"""ajout de la tables statistique et mise à jour des tables existantes

Revision ID: efd20c8ef871
Revises: 3abfe58b0eb1
Create Date: 2026-05-20 11:14:55.603781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'efd20c8ef871'
down_revision: Union[str, Sequence[str], None] = '3abfe58b0eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inscritions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=False),
    sa.Column('prenom', sa.String(length=30), nullable=False),
    sa.Column('sexe', sa.Enum('MASCULIN', 'FEMININ', name='sexe'), nullable=False),
    sa.Column('matricule', sa.String(length=5), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('accepted', 'refused', ''), nullable=True),
    sa.Column('comments', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('telephone')
    )
    op.drop_index(op.f('email'), table_name='demande_inscrition')
    op.drop_index(op.f('matricule'), table_name='demande_inscrition')
    op.drop_index(op.f('telephone'), table_name='demande_inscrition')
    op.drop_table('demande_inscrition')
    op.alter_column('users', 'qrCode',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Enum('admin', 'employe'),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['qrCode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'employe'),
               type_=mysql.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'qrCode',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_table('demande_inscrition',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('sexe', mysql.ENUM('MASCULIN', 'FEMININ'), nullable=False),
    sa.Column('matricule', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('telephone', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('photo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('poste', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('comments', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('telephone'), 'demande_inscrition', ['telephone'], unique=True)
    op.create_index(op.f('matricule'), 'demande_inscrition', ['matricule'], unique=True)
    op.create_index(op.f('email'), 'demande_inscrition', ['email'], unique=True)
    op.drop_table('inscritions')
    # ### end Alembic commands ###
