"""fusion des demandes et des utilisateurs et supression des statistiques

Revision ID: f9ef49bc7735
Revises: 
Create Date: 2026-08-08 11:08:07.326548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ef49bc7735'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=True),
    sa.Column('valeur', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=False),
    sa.Column('prenom', sa.String(length=30), nullable=False),
    sa.Column('sexe', sa.Enum('MASCULIN', 'FEMININ', name='sexe'), nullable=False),
    sa.Column('matricule', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=12), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('poste', sa.String(length=50), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIF', 'INACTIF', 'ACCEPTED', 'REFUSED', 'PENDING', name='statutemploye'), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EMPLOYE', name='roleemploye'), nullable=False),
    sa.Column('request_comments', sa.String(length=255), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('request_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('qr_code'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('pointages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_day', sa.Date(), nullable=False),
    sa.Column('heure_arrive', sa.Time(), nullable=True),
    sa.Column('heure_depart', sa.Time(), nullable=True),
    sa.Column('minutes_travail', sa.Integer(), nullable=True),
    sa.Column('minutes_sup', sa.Integer(), nullable=True),
    sa.Column('numero_pointage', sa.Integer(), nullable=False),
    sa.Column('distance_arrivee', sa.Float(), nullable=True),
    sa.Column('distance_depart', sa.Float(), nullable=True),
    sa.Column('status_arrivee', sa.Enum('ABSENT', 'PENDING', 'PRESENT', 'RETARD', name='scoringstate'), nullable=True),
    sa.Column('status_depart', sa.Enum('ABSENT', 'PENDING', 'PRESENT', 'RETARD', name='scoringstate'), nullable=True),
    sa.Column('photo_pointage_arrivee', sa.String(length=100), nullable=True),
    sa.Column('photo_pointage_depart', sa.String(length=100), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cron_job_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_job_execution_log_job_name'), 'cron_job_execution_log', ['job_name'], unique=False)
    op.create_table('cron_job_state',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('last_run', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('cron_job_status',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('instance_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cron_job_status')
    op.drop_table('cron_job_state')
    op.drop_index(op.f('ix_cron_job_execution_log_job_name'), table_name='cron_job_execution_log')
    op.drop_table('cron_job_execution_log')
    op.drop_table('pointages')
    op.drop_table('users')
    op.drop_table('parametres')
    # ### end Alembic commands ###
